import { type Metadata } from 'next'
import './globals.css'
// import "react-calendar/dist/Calendar.css";
import "@/components/calendar/MiniCalendar.css";
import ThemeProvider from '@/providers/ThemeProvider';
import LayoutStructure from './layoutStructure';

export const metadata: Metadata = {
  title: 'Introduction',
  description: 'Generated by create next app',
  applicationName: 'HCMUT',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  themeColor: '#422AFB',
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'nhatdev',
  authors: [{ name: 'nhatdev' }],
  creator: 'nhatdev'
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <LayoutStructure childrenProps={children} />
        </ThemeProvider>
      </body>
    </html>
  )
}
